swagger: '2.0'
info:
  title: node-go POC
  description: Connect nodejs with go server via websockets
  version: '1.0'
host: 'localhost:2000'
basePath: /v1
schemes:
  - http
paths:
  /users:
    get:
      summary: Returns a list of users.
      operationId: getUsers
      produces:
        - application/json
      responses:
        '200':   
          description: OK
          schema: 
            type: array
            items: 
              $ref: '#/definitions/User'
        '404':
          description: List is empty
          schema:
            $ref: '#/definitions/NotFoundError'
    post:
      summary: Stores a user
      operationId: saveUser
      produces:
        - application/json
      parameters:
        - name: user
          in: body
          schema:
            $ref: '#/definitions/User'
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/User'
        '412':
          description: 'Precondition failed'
          schema:
              $ref: '#/definitions/RequirementsError'


definitions:
  #structs
  User:
    required:
      - name
      - age
    properties:
      id:
        type: integer
        readOnly: true
      name:
        type: string
        minLength: 10
      age:
        type: integer
  #errors
  NotFoundError:
    type: object
    properties:
      code:
        type: integer
      message:
        type: string
  RequirementsError:
    type: object
    properties:
      code:
        type: integer
      message:
        type: string