// Code generated by go-swagger; DO NOT EDIT.

// Package restapi node-go POC
//
//  Connect nodejs with go server via websockets
//  Schemes:
//    http
//  Host: localhost:2000
//  BasePath: /v1
//  Version: 1.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
